import './globals.css'
import styles from "./header.module.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.gnb}>
          <a href="/" className={styles.logo}>
            Logo
          </a>
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
