import Link from "next/link";
import "./globals.css";
import styles from "./header.module.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getCategorys } from "@/service/category";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categorys = await getCategorys();
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.gnb}>
          <Link href="/" className={styles.logo}>
            Logo
          </Link>

          <nav className={styles.navigation}>
            <Link href="/home" className={styles.link}>
              Home
            </Link>

            {categorys.map((category) => (
              <Link
                href={`/category/${category.name}`}
                className={styles.link}
                key={category.id}
              >
                {category.name}
              </Link>
            ))}
          </nav>
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
